### ISSUE TITLE
no code outputed

### ISSUE THREAD

**Issue by romanianstrife** [isaacmorneau/C-3PO#2]
*** mistake made ***

**Comment by romanianstrife** [comment]
I modified the code, and was able to get your program to output self.line, but the code is identical to the original source, no obfuscation

There is a big hole in C obfuscators right now, and you put a lot of effort into this application, it would be awesome if it worked properly...

https://softwarerecs.stackexchange.com/questions/65366/looking-for-c-obfuscator

**Comment by romanianstrife** [comment]
ok, I got it all working, except, the only thing its doing is removing blank lines and comments, is there some other way to trigger more obfuscation?

**Comment by romanianstrife** [comment]
This is the command I am using

```
python3 c3po.py -s release -o output --seed 2353455234 build
Using seed: 2353455234
Parsing:
    [2323:release/release.c]
Resolving:
    [2323:release/release.c]
Writing:
    [2323:release/release.c]

```

Please pardon my ignorance, is there any chance you can let me know what im doing wrong

**Comment by isaacmorneau** [comment]
Hello!

Thank you for showing some interest in this pet project of mine.  This is not like other obfuscates that just magically work this one takes directives to follow specific sets of instructions to do stuff like break signature detection. I'm currently in the middle of rewriting a large portion of it to be more stable before I add more features.

I will be writing up a guide on how to use it after I finish my refactor but for now to find usage 
would be the tests folder. It demos that all the different things it can do right now. The easiest place to start would be by modifying [test.c](https://github.com/isaacmorneau/C-3PO/blob/master/src/test.c) inside of src/ then using cmake to build it. That would roughly work as follows:

```
cd C-3PO/
mkdir bin/
cd bin/
cmake ../
make
```

For all the other things currently supported look through the rest of the tests folder as each one has its own test showing its usage.

Finally as a high level to help understand how this tool works think of it as this:

```
normal source code + the special pragmas -> processed by c3po -> obfuscated source code -> build as desired (gcc, clang, etc.) -> post processed by c3po -> done
```

**Comment by isaacmorneau** [comment]
As a final side comment, if you want to see the intermediate code c3po is generating it is found in gen/ after you call make.

**Comment by romanianstrife** [comment]
Isaac, Thank you for all your effort, I look forward to reading your guide, until then, I will look at the tests and continue reading your code :)

**Comment by romanianstrife** [comment]
Can you tell me what timer does real quick?

**Comment by isaacmorneau** [comment]
Certainly.

Timer is designed to interfere with dynamic analysis. When stepping through code to reverse engineer it the code is frequently halted and as such it takes far longer to complete a given task. So what this does is sets a bounding for maximum (and minimum) allowed execution time. This means that running the code normally nothing happens but when someone slows it down to debug it it triggers as a subtle way to detect that someone is attempting to reverse engineer your code.

This doesn't currently do anything outside of detecting it though. Later on I plan to have it sabotage the encryption/decryption of other parts of the application to render tampering far more difficult.

**Comment by romanianstrife** [comment]
Isaac, Your software was the only C Obfuscator that worked for me. 

https://softwarerecs.stackexchange.com/questions/65366/looking-for-c-obfuscator

Big opportunity here, seize the day!

Take a look at tigress, it has some serious features.

**Comment by romanianstrife** [comment]
I have another question, can I say mangle a name of a define and encrypt the contents?

**Comment by isaacmorneau** [comment]
while defines don't have names so mangling is pointless the content is stored as a literal. To encrypt that use the example found [here](https://github.com/isaacmorneau/C-3PO/blob/master/test/encrypt/encrypt.c) and it will automatically add decryption to all the places its used

**Comment by romanianstrife** [comment]
Thank you
